#!/usr/bin/env bash
# https://stackoverflow.com/questions/2973996/git-rebase-without-changing-commit-timestamps/53516609#53516609
set -eu
echo post-commit
if [ ! "${CIROSANTILLI_GITHOOKS_DISABLE:-0}" = 1 ]; then
  if [ -z "${GIT_COMMITTER_DATE:-}" ]; then
    last_git_time="$(git log --date=format:'%H:%M:%S' --format='%ad' -n 1 --skip 1)"
    last_git_date="$(git log --date=format:'%Y-%m-%d' --format='%ad' -n 1 --skip 1)"
    today="$(date '+%Y-%m-%d')"
    if [ "$last_git_date" = "$today" ]; then
      new_time="${last_git_time}"
      new_delta=' + 1 second'
    else
      new_time="00:00:00"
      new_delta=
    fi
    echo asdf "$last_git_date" = "$today"
    d="$(date --date "${today}T${new_time}+0000${new_delta}" "+${today}T%H:%M:%S+0000")"
    echo "$d"
    CIROSANTILLI_GITHOOKS_DISABLE=1 \
      GIT_COMMITTER_DATE="$d" \
      git commit \
      --amend \
      --date "$d" \
      --no-edit \
      --no-verify \
      &>/dev/null \
    ;
  fi
  echo
fi
