#!/usr/bin/env bash
# https://stackoverflow.com/questions/2973996/git-rebase-without-changing-commit-timestamps/53516609#53516609
set -eu
declare -a olds
declare -A oldnew
while IFS= read -r line; do
  old="$(echo "$line" | cut -d ' ' -f1)"
  new="$(echo "$line" | cut -d ' ' -f2)"
  oldnew[$old]="$new"
  olds+=("$old")
done
echo git reset --hard "${olds[0]}~"
for old in "${olds[@]}"; do
  new="${oldnew[$old]}"
  echo git cherry-pick "$new"
  olddate="$(git log --format='%cd' -n 1 "$old")"
  if [ -z "${GIT_COMMITTER_DATE:-}" ]; then
    echo GIT_COMMITTER_DATE="$olddate" git commit --amend --no-edit &>/dev/null
  fi
done
